name: Joseph Clark
favicon: null
layout_spectrum: 0.9380747494287789
typography_spectrum: 0.5193697861395776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.38024403527379036
  lightness: 0.7576738130301237
  saturation: 0.7128225069027394
  rhythmicContrast: 0.25083864899352193
purpose: []
